<a href="https://colab.research.google.com/github/shivaparihar6119/fake_news_detector/blob/master/fake_news.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/fake_or_real_news.csv")

In [ ]:
df.head()

id                                              title  \
0   8476                       You Can Smell Hillary’s Fear   
1  10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2   3608        Kerry to go to Paris in gesture of sympathy   
3  10142  Bernie supporters on Twitter erupt in anger ag...   
4    875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [ ]:
df.shape

(6335, 4)

In [ ]:
df.dropna()


id                                              title  \
0      8476                       You Can Smell Hillary’s Fear   
1     10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2      3608        Kerry to go to Paris in gesture of sympathy   
3     10142  Bernie supporters on Twitter erupt in anger ag...   
4       875   The Battle of New York: Why This Primary Matters   
...     ...                                                ...   
6330   4490  State Department says it can't find emails fro...   
6331   8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332   8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333   4021  In Ethiopia, Obama seeks progress on peace, se...   
6334   4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 4 columns]

In [ ]:
df['result']=df['label'].apply(lambda x:0 if x=="FAKE" else 1)
df=df.drop("label",axis=1)
df

id                                              title  \
0      8476                       You Can Smell Hillary’s Fear   
1     10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2      3608        Kerry to go to Paris in gesture of sympathy   
3     10142  Bernie supporters on Twitter erupt in anger ag...   
4       875   The Battle of New York: Why This Primary Matters   
...     ...                                                ...   
6330   4490  State Department says it can't find emails fro...   
6331   8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332   8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333   4021  In Ethiopia, Obama seeks progress on peace, se...   
6334   4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text  result  
0     Daniel Greenfield, a Shillman Journalism Fello...       0  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...       0  
2     U.S. Secretary of State John F. Kerry said Mon...       1  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...       0  
4     It's primary day in New York and front-runners...       1  
...                                                 ...     ...  
6330  The State Department told the Republican Natio...       1  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...       0  
6332   Anti-Trump Protesters Are Tools of the Oligar...       0  
6333  ADDIS ABABA, Ethiopia —President Obama convene...       1  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...       1  

[6335 rows x 4 columns]

In [ ]:
print(df['result'].value_counts())

1    3171
0    3164
Name: result, dtype: int64


In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
ps=PorterStemmer()
corp=[]
for i in range(0,len(df)):
    ntxt = re.sub('[^a-zA-Z]', ' ', df['text'][i])
    ntxt = ntxt.lower()
    ntxt = ntxt.split()
    ntxt = [ps.stem(word) for word in ntxt if not word in stopwords.words('english')]
    ntxt=' '.join(ntxt)
    corp.append(ntxt)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
corp[3]

'kayde king kaydeek novemb lesson tonight dem loss time democrat start listen voter stop run establish candid peopl berni peopl berni novemb dem want tight race work berni walker bragman walkerbragman novemb new york time columnist paul krugman one hillari clinton outspoken surrog contenti democrat primari blame clinton poor perform green parti candid jill stein far receiv neglig number vote nation say stein ralph nader prevent clinton victori account berniesteach threw krugman analysi back face candid issu take respons http co khyouusrf teacher berni berniesteach novemb ana navarro republican recent endors hillari clinton sum preposter natur presidenti elect tweet gop nomin damn candid could lose hillari clinton democrat nomin damn candid could lose trump ana navarro ananavarro novemb popular left wing facebook page pro sander primari respond trump surg simpli post meme sander face text could avoid thank noth dnc meme share almost time less hour post tuesday novemb berni sander endors

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect=TfidfVectorizer(max_features=5000,ngram_range=(1,3))
x=vect.fit_transform(corp).toarray()

In [ ]:
y=df['result']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=3)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
from sklearn.svm import LinearSVC
svc_model=LinearSVC()
svc_model.fit(x_train,y_train)
score=svc_model.score(x_test,y_test)
print(score)
y_pred=svc_model.predict(x_test)
cmatrix=confusion_matrix(y_test,y_pred)
print(cmatrix)

0.9263545502367175
[[889  63]
 [ 77 872]]


In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb_model=MultinomialNB()
nb_model.fit(x_train,y_train)
score=nb_model.score(x_test,y_test)
print(score)
y_pred=nb_model.predict(x_test)
cmatrix=confusion_matrix(y_test,y_pred)
print(cmatrix)

0.8769068911099421
[[853  99]
 [135 814]]


In [ ]:
import tensorflow
tensorflow.__version__

'2.15.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense


In [ ]:
voc_size=4000
onehot_repr=[one_hot(words,voc_size)for words in corp]

In [ ]:
sent_len=500
embedd_word=pad_sequences(onehot_repr,maxlen=sent_len,padding='pre')

In [ ]:
embedd_word[0]

array([1127,  542, 1814, 1496, 2204, 2683, 2868,  237, 2381, 1641, 3335,
       1453, 3353, 3925, 2116, 2518, 2128, 3438, 2128, 2518, 2966, 1704,
       3303,  357, 2270, 2418, 3092, 1694, 3972, 1885, 2116, 2188, 1175,
       2518,  617,  341,  617,  341,  196, 3229, 1213, 3074, 1406,  201,
       3682,  188, 3377, 1050, 1246, 2119, 2476, 1453, 3991,  388, 2653,
        135,  617,  341, 2873, 1175, 2866,  827, 2953, 1515, 2381, 3572,
        551, 1245, 2116, 2713, 2014, 3572, 1933, 2953, 1840,  484, 1668,
       2613,  195, 1349, 1270, 2285, 2930,  709, 3572, 2117, 2162, 1288,
       2162, 1185, 2713, 1914, 2634, 1646, 2966,  446, 2075, 1443, 1911,
       2568,  542, 1814, 1496, 2670, 3299, 2978, 3804, 2445, 2623,  874,
       2284, 3446, 2017, 1623,  914,  284,  523, 2293,  579, 2116, 3790,
       2866,  827,  551, 1861, 3961, 2212, 2201,  948, 3019, 1225, 2640,
       1053, 3706,  948, 2725,  119, 3572, 1461, 1485, 3706, 3974, 1654,
       3462, 2739, 2743,  673, 1929, 3472, 3572, 16

In [ ]:
embedded_features=30
model_lstm=Sequential()
model_lstm.add(Embedding(voc_size,embedded_features,input_length=sent_len))
model_lstm.add(LSTM(120))
model_lstm.add(Dense(1,activation='sigmoid'))
model_lstm.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model_lstm.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 500, 30)           120000    
                                                                 
 lstm (LSTM)                 (None, 120)               72480     
                                                                 
 dense (Dense)               (None, 1)                 121       
                                                                 
Total params: 192601 (752.35 KB)
Trainable params: 192601 (752.35 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
x_embedd=np.array(embedd_word)
x_embedd_train,x_embedd_test,y_embedd_train,y_embedd_test=train_test_split(x_embedd,y,test_size=0.3,random_state=3)

In [ ]:
model_lstm.fit(x=x_embedd_train,y=y_embedd_train,epochs=10,batch_size=64)

In [ ]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
# Train the SVM model
model_svm = SVC()
model_svm.fit(x_embedd_train, y_embedd_train)

# Train the Random Forest model
model_rf = RandomForestClassifier()
model_rf.fit(x_embedd_train, y_embedd_train)

NameError: name 'SVC' is not defined

In [ ]:
y_pred_lstm = model.predict(x_embedd_test)
# Combine predictions using Logistic Regression as the meta-classifier
y_pred_svm = model_svm.predict(x_embedd_test)
y_pred_rf = model_rf.predict(x_embedd_test)
X_pred_test = np.column_stack((y_pred_lstm.flatten(), y_pred_svm, y_pred_rf))
meta_classifier = LogisticRegression()
meta_classifier.fit(X_pred_test, y_embedd_test)


In [ ]:
# Make predictions on test data
y_pred_final = meta_classifier.predict(X_pred_test)

# Evaluate the ensemble model
accuracy = accuracy_score(y_embedd_test, y_pred_final)
print("Ensemble model accuracy:", accuracy)

In [ ]:

vect_text=vect.transform([text])
ans=svc_model.predict(vect_text)
print (ans)
print(df['result'][8])